/*
 * Copyright (c) 2024.
 * by 刘铭熙
 */

import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google"
import "./globals.css";

import {cn} from "@/lib/utils"
import React from "react";
import {ThemeProvider} from "@/components/theme/theme-provider";
import {ImageStoreProvider} from "@/providers/counter-store-provider";

import {Toaster} from "@/components/ui/toaster"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create-mi next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <ImageStoreProvider>
                {children}
                <Toaster/>
            </ImageStoreProvider>
        </ThemeProvider>

        </body>
        </html>
    );
}
